name: Build minor alpine image

on:
  schedule: # Always runs on a default branch, docs: <https://git.io/Je5Z7>
    - cron: '0 * * * *' # every 1 hour
  push:
    branches: [develop] # change branch name if you want
    tags-ignore: ['**']

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    env:
      SOURCE_HUB: 'library/node'
      TARGET_HUB: 'tarampampam/node'
    steps:
      - name: Get minor node images (alpine-based) and compare with existing images
        id: info
        run: |
          node_alpine_tags=''
          for page in {1..20}; do
            node_alpine_tags=`echo -n "${node_alpine_tags} $(curl -L -s \
              "https://registry.hub.docker.com/v2/repositories/${SOURCE_HUB}/tags?page=${page}&page_size=2048" |\
              jq -r '.results[] | select(.name | test("^[0-9]+.[0-9]+-alpine$")) | .name | sub("-alpine$"; "") | select(test("^[^1-7]."))' |\
              tr '\n' ' ')" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`
          done;
          exists_alpine_tags=$(curl -L -s \
            "https://registry.hub.docker.com/v2/repositories/${TARGET_HUB}/tags?page_size=2048" |\
            jq -r '.results[] | select(.name | test("^[0-9]+.[0-9]+-alpine$")) | .name | sub("-alpine$"; "")' |\
            tr '\n' ' ' | sed -e 's/[[:space:]]*$//')
          diff=$(comm -23 <(echo "${node_alpine_tags}" | tr ' ' '\n' | sort) <(echo "${exists_alpine_tags}" | tr ' ' '\n' | sort))
          target=$(echo -n "$diff" | sort -V | head -n 1)
          echo -e "Node:\t${node_alpine_tags}\nExists:\t${exists_alpine_tags}\nDiff:\t${diff}\nTarget:\t${target}"
          echo "::set-output name=target::$target"

      - name: Check out code
        if: steps.info.outputs.target != ''
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build docker image
        if: steps.info.outputs.target != ''
        env:
          TARGET_TAG: "${{ steps.info.outputs.target }}-alpine"
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin &> /dev/null
          docker build \
            --build-arg "NODE_VERSION=${TARGET_TAG}" \
            --tag "${TARGET_HUB}:${TARGET_TAG}" \
            -f ./Dockerfile.alpine .
          docker push "${TARGET_HUB}:${TARGET_TAG}"
